kind: pipeline
type: docker
name: Update csv to GitHub

steps:
- name: Generate output and push to GitHub
  image: rocker/geospatial:4.2.3
  volumes:
  - name: renv_paths_cache_host
    path: /renv/cache
  environment:
    RENV_PATHS_CACHE: /renv/cache
    RENV_VERSION: 0.17.3
  commands:
  - R -e "renv::restore()"
  - Rscript run_all.R
  - git config user.name "github-actions[bot]"
  - git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
  - git add output/
  - git commit -m "update csv 😬👍"
  - git push

volumes:
- name: renv_paths_cache_host
  host:
    path: /opt/local/renv/cache
