kind: pipeline
type: docker
name: Update csv to GitHub

steps:
- name: Generate output and upload to Gist
  image: rocker/geospatial:4.2.3
  volumes:
  - name: renv_paths_cache_host
    path: /renv/cache
  - name: shp_cache
    path: /drone/src/data
  environment:
    RENV_PATHS_CACHE: /renv/cache
    RENV_VERSION: 0.17.3
    GIST_ACCESS_TOKEN:
      from_secret: gist_access_token
  commands:
  - R -e "renv::restore()"
  - |
     if [ ! -d "/drone/src/data/village_shp" ]; then
        Rscript R/utils/village_shp_downloader.R
     fi
  - Rscript run_all.R
  - FILE_CONTENT=$(sed ':a;N;$!ba;s/\n/ /g' output/village.csv)
  - |
    curl -L \
    -X PATCH \
    -H "Accept: application/vnd.github+json" \
    -H "Authorization: Bearer $GIST_ACCESS_TOKEN" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    https://api.github.com/gists/c89e393f583ced2cf53298f322e5a294 \
    -d "{\"files\":{\"commusidewalk-data.csv\":{\"content\":$FILE_CONTENT}}}"

volumes:
- name: renv_paths_cache_host
  host:
    path: /opt/local/renv/cache
- name: shp_cache
  host:
    path: /opt/local/commusidewalk-data/cache
