kind: pipeline
type: docker
name: Update csv to GitHub

steps:

- name: Generate output and push to GitHub
  image: rocker/geospatial:4.2.3
  volumes:
  - name: renv_paths_cache_host
    path: /renv/cache
  - name: shp_cache
    path: /drone/src/data
  environment:
    RENV_PATHS_CACHE: /renv/cache
    RENV_VERSION: 0.17.3
    SSH_KEY:
      from_secret: ssh_key
  commands:
  - echo $SSH_KEY > private_key
  - export GIT_SSH_COMMAND='ssh -i private_key $ -o IdentitiesOnly=yes'
  - R -e "renv::restore()"
  - |
     if [ ! -d "/drone/src/data/village_shp" ]; then
        Rscript R/utils/village_shp_downloader.R
     fi
  - Rscript run_all.R
  - git config --global url."git@github.com:".insteadOf "https://github.com/"
  - git config user.name "github-actions[bot]"
  - git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
  - git add output/
  - git commit -m "update csv 😬👍"
  - git push git@github.com:CommuSidewalk/commusidewalk-data.git

volumes:
- name: renv_paths_cache_host
  host:
    path: /opt/local/renv/cache
- name: shp_cache
  host:
    path: /opt/local/commusidewalk-data/cache
