CREATE TABLE IF NOT EXISTS general_events (
  event_id INTEGER PRIMARY KEY,
  occurrence_date DATE,
  longitude VARCHAR(255),
  latitude VARCHAR(255),
  accident_category_name VARCHAR(255),
  handling_unit_name_police_department_level VARCHAR(255),
  location VARCHAR(255),
  weather_name VARCHAR(255),
  lighting_name VARCHAR(255),
  road_category_first_party_name VARCHAR(255),
  speed_limit_first_party SMALLINT,
  road_type_main_category_name VARCHAR(255),
  road_type_sub_category_name VARCHAR(255),
  accident_location_main_category_name VARCHAR(255),
  accident_location_sub_category_name VARCHAR(255),
  road_condition_paving_name VARCHAR(255),
  road_condition_surface_status_name VARCHAR(255),
  road_condition_surface_defect_name VARCHAR(255),
  road_obstacle_obstacle_name VARCHAR(255),
  road_obstacle_visibility_quality_name VARCHAR(255),
  road_obstacle_visibility_name VARCHAR(255),
  traffic_light_signal_type_name VARCHAR(255),
  traffic_light_signal_action_name VARCHAR(255),
  lane_division_facility_main_category_name VARCHAR(255),
  lane_division_facility_sub_category_name VARCHAR(255),
  lane_division_facility_fast_lane_or_general_lane_name VARCHAR(255),
  lane_division_facility_fast_slow_lane_name VARCHAR(255),
  lane_division_facility_road_edge_line_name VARCHAR(255),
  accident_type_and_category_main_category_name VARCHAR(255),
  accident_type_and_category_sub_category_name VARCHAR(255),
  cause_classification_main_category_name_primary VARCHAR(255),
  cause_classification_sub_category_name_primary VARCHAR(255),
  number_of_deaths SMALLINT,
  number_of_injuries SMALLINT
);
